# Create image with all Looker nodes
FROM misterblue/ros2-looker-base

RUN echo UTC > /etc/timezone

# Tell the libraries not to use the interactive dialogs
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux

# Change to the non-root user so after this is all app space
env USER=nonroot
USER $USER

# Get the node code
RUN cd \
    && git clone https://github.com/Misterblue/ros2-looker.git \
    && cd ros2-looker \
    && . /opt/ros/foxy/setup.sh \
    && colcon build

COPY --chown=${USER}:${USER} files/looker-start.sh /home/${USER}

# NOTE reference to USER. This command doesn't do the substitution in strings
ENTRYPOINT [ "/usr/bin/tini", "--", "/home/look/looker-start.sh" ]
# Default arguments for your app (remove if you have none)
# CMD [ "--foo", "1", "--bar=2" ]
