# Create image with all Looker nodes
FROM misterblue/ros2-looker-base

RUN echo UTC > /etc/timezone

# Tell the libraries not to use the interactive dialogs
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux

env USER=nonroot

# Add the user to the 'video' group in case it wants to use the camera
RUN usermod -a -G video ${USER}

# Change to the non-root user so after this is all app space
USER ${USER}

# Get the node code
RUN cd \
    && git clone https://github.com/Misterblue/ros2-looker.git \
    && cd ros2-looker \
    && . /opt/ros/foxy/setup.sh \
    && colcon build

COPY --chown=${USER}:${USER} files/looker-start.sh /home/${USER}

USER ${USER}:${USER}
WORKDIR /home/${USER}

ENTRYPOINT [ "./looker-start.sh" ]
